server:
  port: 8930
  # 应用的访问路径
  session-timeout: 5000
  servlet:
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    open: true
    port: 5672
# 日志配置
logging:
  level:
    com.chiste: debug

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.chiste.novel.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
swagger:
  enable: true
#generate
generate:
  tableName: t_sys_user
  entityName: SysUser
  domainPackage: com.chiste.novel.domain
  mapperPackage: com.chiste.novel.mapper
  xmlPackage: mapper



