
-- 管理员
INSERT INTO `novel`.`t_sys_user` (`id`, `user_code`, `user_name`, `password`, `salt`, `gender`, `email`, `phone_number`) VALUES (1, 'admin', '管理员', '27bd386e70f280e24c2f4f2a549b82cf', NULL, 0, NULL, '17746043623');

-- 爬虫源
INSERT INTO `novel`.`t_crawl_source` (`id`, `source_name`, `crawl_rule`, `source_status`, `create_time`, `update_time`, `source_url`, `source_cat_id`) VALUES (6, '新笔趣阁', '{\n	\"bookListUrl\": \"http://www.xbiquge.la/fenlei/{catId}_{page}.html\",\n	\"catIdRule\": {\n		\"catId1\": \"1\",\n		\"catId2\": \"2\",\n		\"catId3\": \"3\",\n		\"catId4\": \"4\",\n		\"catId5\": \"6\",\n		\"catId6\": \"5\"\n	},\n	\"bookIdPatten\": \"<a\\\\s+href=\\\"http://www.xbiquge.la/(\\\\d+/\\\\d+)/\\\"\\\\s+target=\\\"_blank\\\">\",\n	\"pagePatten\": \"<em\\\\s+id=\\\"pagestats\\\">(\\\\d+)/\\\\d+</em>\",\n	\"totalPagePatten\": \"<em\\\\s+id=\\\"pagestats\\\">\\\\d+/(\\\\d+)</em>\",\n	\"bookDetailUrl\": \"http://www.xbiquge.la/{bookId}/\",\n	\"bookNamePatten\": \"<h1>([^/]+)</h1>\",\n	\"authorNamePatten\": \"者：([^/]+)</p>\",\n	\"picUrlPatten\": \"src=\\\"(http://www.xbiquge.la/files/article/image/\\\\d+/\\\\d+/\\\\d+s\\\\.jpg)\\\"\",\n	\"bookStatusRule\": {},\n	\"descStart\": \"<div id=\\\"intro\\\">\",\n	\"descEnd\": \"</div>\",\n	\"upadateTimePatten\": \"<p>最后更新：(\\\\d+-\\\\d+-\\\\d+\\\\s\\\\d+:\\\\d+:\\\\d+)</p>\",\n	\"upadateTimeFormatPatten\": \"yyyy-MM-dd HH:mm:ss\",\n	\"bookIndexUrl\": \"http://www.xbiquge.la/{bookId}/\",\n	\"indexIdPatten\": \"<a\\\\s+href=\'/\\\\d+/\\\\d+/(\\\\d+)\\\\.html\'\\\\s+>[^/]+</a>\",\n	\"indexNamePatten\": \"<a\\\\s+href=\'/\\\\d+/\\\\d+/\\\\d+\\\\.html\'\\\\s+>([^/]+)</a>\",\n	\"bookContentUrl\": \"http://www.xbiquge.la/{bookId}/{indexId}.html\",\n	\"contentStart\": \"<div id=\\\"content\\\">\",\n	\"contentEnd\": \"<p>\"\n}', 0, '2020-05-23 22:46:58', '2020-05-23 22:46:58', 'http://www.xbiquge.la/', NULL);
INSERT INTO `novel`.`t_crawl_source` (`id`, `source_name`, `crawl_rule`, `source_status`, `create_time`, `update_time`, `source_url`, `source_cat_id`) VALUES (7, '久久小说', '{\"bookListUrl\": \"http://www.jjxsxzw.com/{catUrl}/{pageUrl}\",\"catUrlRule\": {\"catId16\": \"/txt/Chuanyue/\",\"catId17\": \"/txt/chongshengxiaoshuo/\",\"catId18\": \"/txt/Lsjs/\",\"catId19\": \"/txt/Qinggan/\",\"catId20\": \"/txt/Young/\"},\"bookIdPatten\": \"<a\\\\s+href=\\\"/txt/(\\\\d{1,}.htm)/\\\"\\\\s+title=\\\"([\\\\u4E00-\\\\u9FA5A-Za-z0-9_\\\\[\\\\]\\\\（\\\\）\\\\{\\\\}\\\\<\\\\>]{1,})\\\"\\\\s+target=\\\"_blank\\\">\",\"pagePatten\": \"<b>(\\\\d+)/\\\\d+</b>\",\"totalPagePatten\": \"<a\\\\s+title=\\\"总数\\\">\\\\d+/(\\\\d+)</a>\",\"bookDetailUrl\": \"http://www.jjxsxzw.com/{bookId}\",\"bookNamePatten\": \"<h1>([^/]+)</h1>\",\"authorNamePatten\": \"<li\\\\s+class=\\\"zuozhe\\\"><a>([^/]+)</a></li>\",\"picUrlPatten\": \"src=\\\"(http://img.jjxsxzw.com/UploadPic/2021-04/\\\\d+/\\\\d+/\\\\d+s\\\\.jpg)\\\"\",\"bookStatusRule\": {},\"descStart\": \"<div\\\\s+id=\\\"mainSoftIntro\\\">\",\"descEnd\": \"</div>\",\"upadateTimePatten\": \"<li><b>最后更新：</b>(\\\\d+-\\\\d+-\\\\d+\\\\s\\\\d+:\\\\d+:\\\\d+)</li>\",\"upadateTimeFormatPatten\": \"yyyy-MM-dd HH:mm:ss\",\"bookIndexUrl\": \"http://www.jjxsxzw.com/txt/{bookId}\",\"downloadUrlPatten\": \"<li\\\\s+class=\\\"downAddress_li\\\"><a\\\\s+href=\\\"/txt/(\\\\d+/\\\\d+)/\\\"></a></li>\",\"downloadUrl\": \"<a\\\\s+href=\\\"(\\\\d+/\\\\d+)\\\"\\\\s+class=\\\"strong\\\\s+green\\\">\"}', 0, '2021-04-26 10:53:06', '2021-04-26 10:53:09', 'http://www.jjxsxzw.com/', 'navber');

-- 爬虫源分类数据
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (16, 7, '穿越小说', '/txt/Chuanyue/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (17, 7, '重生小说', '/txt/chongshengxiaoshuo/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (18, 7, '历史架空古装', '/txt/Lsjs/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (19, 7, '总裁豪门', '/txt/Qinggan/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (20, 7, '青春校园现言', '/txt/Young/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (21, 7, '修真仙侠幻想', '/txt/Wuxia/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (22, 7, '同人小说', '/txt/tongrenxiaoshuo/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (23, 7, '网游小说', '/txt/Juben/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (24, 7, '耽美小说', '/txt/dmtr/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (25, 7, '玄幻小说', '/txt/Xuanhuan/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (26, 7, '都市异能娱乐爽文', '/txt/dushi/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (27, 7, '历史架空铁血军旅', '/txt/tiexue/');
INSERT INTO `novel`.`t_crawl_novel_cat` (`id`, `source_id`, `cat_name`, `cat_href`) VALUES (28, 7, '恐怖惊悚悬疑推理', '/txt/Kongbu/');


INSERT INTO `novel`.`t_novel_cat` (`id`, `cat_code`, `cat_name`, `sort`, `create_time`, `create_user`, `update_time`, `update_user`) VALUES (50, '64', '历史架空', 1, '2021-06-09 17:44:40', 0, '2021-06-09 17:44:40', NULL);
